### ISSUE TITLE
Postgres development files are required

### ISSUE THREAD

**Issue by chirvo** [abhiaiyer91/meteor-instagram-apollo#1]
When running npm install, node-gyp fails installing libpq@1.8.2 because it can't find pg_config. This can be solved installing the proper package on your system. On Ubuntu, for example:

sudo apt install libpq-dev

Thanks

**Comment by abhiaiyer91** [comment]
This repo shouldn't have any Postgres attached, my mistake. Will fix

**Comment by bryanterrell** [comment]
Rather than install anything I just ran `npm uninstall pg pg-hstore pg-native --save`

**Comment by abhiaiyer91** [comment]
@bryanterrell thanks, do you mind submitting a PR !

**Comment by bryanterrell** [comment]
Sure thing!
